/* Release data layer (generated by scripts/fetch-releases.mjs).

 * Platform ids match src/scripts/platform.ts minus the 'windows' umbrella —
 * asset files carry concrete architectures:
 *   win-x64       NSIS installer
 *   darwin-arm64  Apple Silicon .dmg
 *   darwin-x64    Intel .dmg
 *   linux         AppImage
 */

import type { Platform } from '../scripts/platform';
import releasesData from './releases.json' with { type: 'json' };

export interface ReleaseAsset {
  name: string;
  /** Concrete asset platform; null when the fetch script could not classify it. */
  platform: 'win-x64' | 'darwin-arm64' | 'darwin-x64' | 'linux' | null;
  url: string;
  size: number | null;
  digest: string | null;
}

export interface Release {
  version: string;
  name: string;
  publishedAt: string | null;
  prerelease: boolean;
  body: string;
  assets: ReleaseAsset[];
}

const releases: Release[] = releasesData as Release[];

/** Map the website's user-facing Platform to the concrete asset platform. */
const ASSET_PLATFORM: Partial<Record<Platform, NonNullable<ReleaseAsset['platform']>>> = {
  windows: 'win-x64',
  'macos-arm': 'darwin-arm64',
  'macos-intel': 'darwin-x64',
  linux: 'linux',
};

function byNewestFirst(list: Release[]): Release[] {
  return [...list].sort((a, b) => {
    const ta = Date.parse(a.publishedAt ?? '') || 0;
    const tb = Date.parse(b.publishedAt ?? '') || 0;
    if (ta !== tb) return tb - ta;
    return b.version.localeCompare(a.version, undefined, { numeric: true });
  });
}

/** All releases, newest first (stable sort). */
export function getReleases(): Release[] {
  return byNewestFirst(releases);
}

/** The most recently published stable release (prereleases excluded). */
export function getLatestRelease(): Release {
  const stable = releases.filter((r) => !r.prerelease);
  const list = stable.length > 0 ? stable : releases;
  const [latest] = byNewestFirst(list);
  if (!latest) {
    throw new Error('releases: no releases present — run `npm run fetch:releases`.');
  }
  return latest;
}

/**
 * Most recent release that ships an asset for the given user-facing platform.
 * Returns null (does not throw) when no release has that asset — e.g.
 * darwin-arm64 before v0.2.x.
 */
export function findLatestForPlatform(p: Platform): Release | null {
  const assetPlatform = ASSET_PLATFORM[p];
  if (!assetPlatform) return null;
  for (const release of byNewestFirst(releases)) {
    if (release.prerelease) continue;
    if (release.assets.some((a) => a.platform === assetPlatform)) return release;
  }
  return null;
}
